export default {
  RESET_PASSWORD: 'RESET_PASSWORD',
  ACTIVATE_ACCOUNT: 'ACTIVATE_ACCOUNT',
  NEWSLETTER: 'NEWSLETTER',
  SPECIAL_SALE: 'SPECIAL_SALE',
  BUY_RECEIPT: 'BUY_RECEIPT',
  RECYCLE_RECEIPT: 'RECYCLE_RECEIPT'
}