module.exports = {
  LIST_CLIENTS: 'LIST_CLIENTS',
  UPDATE_CLIENTS: 'UPDATE_CLIENTS',
  LIST_SERVICES: 'LIST_SERVICES',
  UPDATE_SERVICES: 'UPDATE_SERVICES',
  LIST_PRODUCTS: 'LIST_PRODUCTS',
  UPDATE_PRODUCTS: 'UPDATE_PRODUCTS',
  LIST_VISITS: 'LIST_VISITS',
  UPDATE_VISITS: 'UPDATE_VISITS',
  LIST_STAFFS: 'LIST_STAFFS',
  UPDATE_STAFFS: 'UPDATE_STAFFS',
  UPDATE_WEB_ITEMS: 'UPDATE_WEB_ITEMS'
}
